### ISSUE TITLE
does this work with octave?

### ISSUE THREAD

**Issue by AIAdventures** [zi-w/Max-value-Entropy-Search#1]
Just wondering if the code can be used with open source products?
Best,
Andrew

**Comment by zi-w** [comment]
Hi! I only tried Matlab because it is a research prototype. The idea should be simple enough to implement in other languages (the corresponding paper is free and available online). I plan to integrate it into another project in python but I am not sure when I will finish it. You are welcome to implement in your preferred language and I might be able to help to debug if you post problems here.
